### PR TITLE
Add tinyhttp to the list of web frameworks

### PR DESCRIPTION
**Pull request by v1rtl**
tinyhttp is a modern Express-like web framework written in TypeScript and compiled to native ESM, that uses a bare minimum amount of dependencies trying to avoid legacy hell.

some stats:

- stars: >380
- downloads: >12K

[repo link](https://github.com/talentlessguy/tinyhttp)

### CODE REVIEW

**Comment by AbdouTlili** [comment]
tinyhttp added

**Review by AbdouTlili — APPROVED** [review]

**Comment by v1rtl** [comment]
nice, can these be merged?

**Comment by AbdouTlili** [comment]
sadly i dont have the write access to do it my self

**Comment by v1rtl** [comment]
@AbdouTlili oh ok :c

**Comment by zeabdelkhalek** [comment]
@aravindnc Please check this.

**Review by aravindnc — COMMENTED** [review]
Thanks. Merging.

**Comment by v1rtl** [comment]
> Thanks. Merging.

sorry for replying to edited message, but 0-legacy means without depending on polyfills and outdated packages

**Comment by v1rtl** [comment]
and thanks for merging it :D

**Comment by aravindnc** [comment]
> > Thanks. Merging.
> 
> sorry for replying to edited message, but 0-legacy means without depending on polyfills and outdated packages

Sorry I thought it was a typo. So I checked the package page and verified the info.

**Pull request merged**
